import * as React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../styles/Home.module.css'

export default function Home({ context }) {
  const [clientSide, setClientSide] = React.useState('')
  const router = useRouter()

  React.useEffect(() => {
    setClientSide(JSON.stringify(router, null, '\t'))
  }, [router])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Country</h1>

        <h2>Context</h2>
        <pre>{JSON.stringify(context, null, '\t')}</pre>
        <h2>Router - Client</h2>
        <pre>{clientSide}</pre>
      </main>
    </div>
  )
}

export function getServerSideProps(context) {
  console.log('ctx', context)
  return {
    props: {
      context: {
        query: context.query,
        params: context.params,
        locale: context.locale,
      },
    },
  }
}
